services:
  npm:
    profiles: ["production-proxy"]

  backend:
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      CORS_ALLOW_ORIGIN: http://127.0.0.1:3080

  frontend:
    ports:
      - "127.0.0.1:3080:3000"

  rabbitmq:
    ports:
      - "127.0.0.1:15672:15672"

  minio:
    ports:
      - "127.0.0.1:9100:9000"
      - "127.0.0.1:9101:9001"

  knowledge-video-api:
    ports:
      - "127.0.0.1:8080:8080"

  code-video-api:
    ports:
      - "127.0.0.1:8081:8080"
